<?php
// $Id: ping.module,v 1.35.2.1 2006/07/02 20:53:52 killes Exp $

/**
 * @file
 * Alerts other sites that your site has been updated.
 */

/**
 * Implementation of hook_help().
 */
function ping_help($section) {
  switch ($section) {
    case 'admin/help#ping':
      $output = '<p>'. fo_1_text('The ping module is useful for notifying interested sites that your site has changed.  It automatically sends notifications (called "pings") to the <a href="%external-http-pingomatic-com">pingomatic</a> service to tell it that your site has changed. In turn pingomatic will ping other services such as weblogs.com, Technorati, blo.gs, BlogRolling, Feedster.com, Moreover, etc.', array('%external-http-pingomatic-com' => 'http://pingomatic.com/')) .'</p>';
      $output .= '<p>'. fo_1_text('The ping module requires <code>cron</code> or a similar periodic job scheduler to be enabled.') .'</p>';
      $output .= fo_1_text('<p>You can:</p>
<ul>
<li> enable or disable the ping module at <a href="%admin-modules">administer &gt;&gt; modules</a>.</li>
<li>run your cron job at your sites <a href="%file-cron">cron page</a>.</li>
<li>read about <a href="%external-http-fireorb.info-node-23714">configuring cron jobs</a>.</li>
</ul></p>
', array('%admin-modules' => fo_1_url('admin/modules'), '%file-cron' => 'cron.php', '%external-http-fireorb.info-node-23714' => 'http://fireorb.info/node/23714'));
      $output .= '<p>'. fo_1_text('For more information please read the configuration and customization handbook <a href="%ping">Ping page</a>.', array('%ping' => 'http://fireorb.info/handbook/modules/ping/')) .'</p>';
      return $output;
    case 'admin/modules#description':
      return fo_1_text('Alerts other sites when your site has been updated.');
  }
}

/**
 * Implementation of hook_cron().
 *
 * Fire off notifications of updates to remote sites.
 */
function ping_cron() {
  global $base_url;

  if (fo_1_variable_get('site_name', 0) && fo_1_variable_get('site_slogan', 0)) {
    if (db_num_rows(db_query("SELECT nid FROM {node} WHERE status = 1 AND moderate = 0 AND (created > '". fo_1_variable_get('cron_last', time()) ."' OR changed > '". fo_1_variable_get('cron_last', time()) ."')"))) {
      _ping_notify(fo_1_variable_get('site_name', '') .' - '. fo_1_variable_get('site_slogan', ''), $base_url);
    }
  }
}

/**
 * Call hook_ping() in all modules to notify remote sites that there is
 * new content at this one.
 */
function _ping_notify($name, $url) {
  module_invoke_all('ping', $name, $url);
}

/**
 * Implementation of hook_ping().
 *
 * Notifies pingomatic.com, blo.gs, and technorati.com of changes at this site.
 */
function ping_ping($name = '', $url = '') {

  $result = fo_1_xmlrpc('http://rpc.pingomatic.com', 'weblogUpdates.ping', $name, $url);

  if ($result === FALSE) {
    fo_1_watchdog('directory ping', fo_1_text('Failed to notify pingomatic.com (site).'), WATCHDOG_WARNING);
  }
}


