<?php
// $Id: path.module,v 1.83.2.3 2007/01/04 22:01:17 killes Exp $

/**
 * @file
 * Enables users to rename URLs.
 */

/**
 * Implementation of hook_help().
 */
function path_help($section) {
  switch ($section) {
    case 'admin/help#path':
      $output = '<p>'. fo_1_text('The path module allows you to specify aliases for FireOrb URLs.  Such aliases improve readability of URLs for your users and may help internet search engines to index your content more effectively.  More than one alias may be created for a given page.') .'</p>';
      $output .= fo_1_text('<p>Some examples of URL aliases are:</p>
<ul>
<li>user/login =&gt; login</li>
<li>image/tid/16 =&gt; store</li>
<li>taxonomy/term/7+19+20+21 =&gt; store/products/whirlygigs</li>
<li>node/3 =&gt; contact</li>
</ul>
');
      $output .= '<p>'. fo_1_text('The path module enables an extra field for aliases in all node input and editing forms (when users have the appropriate permissions).  It also provides an interface to view and edit all URL aliases.  The two permissions are related to URL aliasing are "administer a list of URL aliases" and "add url aliases".  ') .'</p>';
      $output .= '<p>'. fo_1_text('This module also comes with user-defined mass URL aliasing capabilities, which is useful if you wish to uniformly use URLs different from the default.  For example, you may want to have your URLs presented in a different language. Access to the FireOrb source code on the web server is required to set up these kinds of aliases. ') .'</p>';
      $output .= fo_1_text('<p>You can</p>
<ul>
<li>set the path for a post with the path module.</li>
<li>add a URL alias: <a href="%admin-path-add">administer &gt;&gt; url aliases &gt;&gt; add alias</a>.</li>
<li>administer the list of URL aliases: <a href="%admin-path">administer &gt;&gt; url aliases</a>.</li>
<li>read how to <a href="%external-http-fireorb.info-node-15365">configure clean URLs</a> for your webserver.
<li>enable clean url\'s to remove the =? at <a href="%admin-settings">administer &gt;&gt; settings</a>.</li>
</ul>
', array('%admin-path-add' => fo_1_url('admin/path/add'), '%admin-path' => fo_1_url('admin/path'), '%external-http-fireorb.info-node-15365' => 'http://fireorb.info/node/15365', '%admin-settings' => fo_1_url('admin/settings')));
      $output .= '<p>'. fo_1_text('For more information please read the configuration and customization handbook <a href="%path">Path page</a>.', array('%path' => 'http://fireorb.info/handbook/modules/path/')) .'</p>';
      return $output;
    case 'admin/modules#description':
      return fo_1_text('Allows users to rename URLs.');
    case 'admin/path':
      return fo_1_text("<p>FireOrb provides users complete control over URLs through aliasing.  This feature is typically used to make URLs human-readable or easy to remember.  For example, one could map the relative URL 'node/1' onto 'about'. Each system path can have multiple aliases.</p>");
    case 'admin/path/add':
      return fo_1_text('<p>Enter the path you wish to create the alias for, followed by the name of the new alias.</p>');
  }
}

/**
 * Implementation of hook_menu().
 */
function path_menu($may_cache) {
  $items = array();

  if ($may_cache) {
    $items[] = array('path' => 'admin/path', 'title' => fo_1_text('url aliases'),
      'callback' => 'path_admin',
      'access' => user_access('administer url aliases'));
    $items[] = array('path' => 'admin/path/edit', 'title' => fo_1_text('edit alias'),
      'callback' => 'path_admin_edit',
      'access' => user_access('administer url aliases'),
      'type' => MENU_CALLBACK);
    $items[] = array('path' => 'admin/path/delete', 'title' => fo_1_text('delete alias'),
      'callback' => 'path_admin_delete_confirm',
      'access' => user_access('administer url aliases'),
      'type' => MENU_CALLBACK);
    $items[] = array('path' => 'admin/path/list', 'title' => fo_1_text('list'),
      'type' => MENU_DEFAULT_LOCAL_TASK, 'weight' => -10);
    $items[] = array('path' => 'admin/path/add', 'title' => fo_1_text('add alias'),
      'callback' => 'path_admin_edit',
      'access' => user_access('administer url aliases'),
      'type' => MENU_LOCAL_TASK);
  }

  return $items;
}

/**
 * Menu callback; presents an overview of all URL aliases.
 */
function path_admin() {
  return path_overview();
}

/**
 * Menu callback; handles pages for creating and editing URL aliases.
 */
function path_admin_edit($pid = 0) {
  if ($pid) {
    $alias = path_load($pid);
    fo_1_set_title(fo_1_check_plain($alias['dst']));
    $output = path_form(path_load($pid));
  }
  else {
    $output = path_form();
  }

  return $output;
}

/**
 * Menu callback; confirms deleting an URL alias
 **/
function path_admin_delete_confirm($pid) {
  $path = path_load($pid);
  if (user_access('administer url aliases')) {
    $form['pid'] = array('#type' => 'value', '#value' => $pid);
    $output = confirm_form('path_admin_delete_confirm', $form,
  fo_1_text('Are you sure you want to delete path alias %title?', array('%title' => theme('placeholder', $path['dst']))),
   $_GET['destination'] ? $_GET['destination'] : 'admin/path', fo_1_text('This action cannot be undone.'),
  fo_1_text('Delete'), fo_1_text('Cancel') );
  }

  return $output;
}

/**
 * Execute URL alias deletion
 **/
function path_admin_delete_confirm_submit($form_id, $form_values) {
  if ($form_values['confirm']) {
    path_admin_delete($form_values['pid']);
    return 'admin/path';
  }
}

/**
 * Post-confirmation; delete an URL alias.
 */
function path_admin_delete($pid = 0) {
  db_query('DELETE FROM {url_alias} WHERE pid = %d', $pid);
  fo_1_set_message(fo_1_text('The alias has been deleted.'));
}



/**
 * Set an aliased path for a given FireOrb path, preventing duplicates.
 */
function path_set_alias($path = NULL, $alias = NULL, $pid = NULL) {
  if ($path && !$alias) {
    db_query("DELETE FROM {url_alias} WHERE src = '%s'", $path);
    fo_1_clear_path_cache();
  }
  else if (!$path && $alias) {
    db_query("DELETE FROM {url_alias} WHERE dst = '%s'", $alias);
    fo_1_clear_path_cache();
  }
  else if ($path && $alias) {
    $path = urldecode($path);
    $path_count = db_result(db_query("SELECT COUNT(src) FROM {url_alias} WHERE src = '%s'", $path));
    $alias = urldecode($alias);
    $alias_count = db_result(db_query("SELECT COUNT(dst) FROM {url_alias} WHERE dst = '%s'", $alias));

    // We have an insert:
    if ($path_count == 0 && $alias_count == 0) {
      db_query("INSERT INTO {url_alias} (src, dst) VALUES ('%s', '%s')", $path, $alias);
      fo_1_clear_path_cache();
    }
    else if ($path_count >= 1 && $alias_count == 0) {
      if ($pid) {
        db_query("UPDATE {url_alias} SET dst = '%s', src = '%s' WHERE pid = %d", $alias, $path, $pid);
      }
      else {
        db_query("INSERT INTO {url_alias} (src, dst) VALUES ('%s', '%s')", $path, $alias);
      }
      fo_1_clear_path_cache();
    }
    else if ($path_count == 0 && $alias_count == 1) {
      db_query("UPDATE {url_alias} SET src = '%s' WHERE dst = '%s'", $path, $alias);
      fo_1_clear_path_cache();
    }
    else if ($path_count == 1 && $alias_count == 1) {
      // This will delete the path that alias was originally pointing to:
      path_set_alias(NULL, $alias);
      path_set_alias($path);
      path_set_alias($path, $alias);
    }
  }
}

/**
 * Return a form for editing or creating an individual URL alias.
 */
function path_form($edit = '') {

  $form['src'] = array('#type' => 'textfield', '#title' => fo_1_text('Existing system path'), '#default_value' => $edit['src'], '#maxlength' => 64, '#description' => fo_1_text('Specify the existing path you wish to alias. For example: node/28, forum/1, taxonomy/term/1+2.'));
  $form['dst'] = array('#type' => 'textfield', '#default_value' => $edit['dst'], '#maxlength' => 64, '#description' => fo_1_text('Specify an alternative path by which this data can be accessed.  For example, type "about" when writing an about page.  Use a relative path and don\'t add a trailing slash or the URL alias won\'t work.'));

  if ($edit['pid']) {
    $form['pid'] = array('#type' => 'hidden', '#value' => $edit['pid']);
    $form['submit'] = array('#type' => 'submit', '#value' => fo_1_text('Update alias'));
  }
  else {
    $form['submit'] = array('#type' => 'submit', '#value' => fo_1_text('Create new alias'));
  }

  return fo_1_get_form('path_form', $form);
}

/**
 * Implementation of hook_nodeapi().
 *
 * Allows URL aliases for nodes to be specified at node edit time rather
 * than through the administrative interface.
 */
function path_nodeapi(&$node, $op, $arg) {
  if (user_access('create url aliases') || user_access('administer url aliases')) {
    switch ($op) {
      case 'validate':
        $node->path = trim($node->path);
        if ($node->path && !fo_1_valid_url($node->path)) {
          form_set_error('path', fo_1_text('The path is invalid.'));
        }
        else if (db_result(db_query("SELECT COUNT(dst) FROM {url_alias} WHERE dst = '%s' AND src != '%s'", $node->path, "node/$node->nid"))) {
          form_set_error('path', fo_1_text('The path is already in use.'));
        }
        break;

      case 'load':
        $path = "node/$node->nid";
        // We don't use fo_1_get_path_alias() to avoid custom rewrite functions.
        // We only care about exact aliases.
        $result = db_query("SELECT dst FROM {url_alias} WHERE src = '%s'", $path);
        if (db_num_rows($result)) {
          $node->path = db_result($result);
        }
        break;

      case 'insert':
        // Don't try to insert if path is NULL.  We may have already set
        // the alias ahead of time.
        if ($node->path) {
          path_set_alias("node/$node->nid", $node->path);
        }
        break;

      case 'update':
        path_set_alias("node/$node->nid", $node->path, $node->pid);
        break;

      case 'delete':
        $path = "node/$node->nid";
        if (fo_1_get_path_alias($path) != $path) {
          path_set_alias($path);
        }
        break;
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function path_form_alter($form_id, &$form) {
  if (user_access('create url aliases') && isset($form['type']) && $form['type']['#value'] .'_node_form' == $form_id) {
    $path = $form['#node']->path;
    $form['path'] = array(
      '#type' => 'fieldset',
      '#title' => fo_1_text('URL path settings'),
      '#collapsible' => TRUE,
      '#collapsed' => empty($path),
      '#weight' => 30,
    );
    $form['path']['path'] = array(
      '#type' => 'textfield',
      '#default_value' => $path,
      '#maxlength' => 250,
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#description' => fo_1_text('Optionally specify an alternative URL by which this node can be accessed.  For example, type "about" when writing an about page.  Use a relative path and don\'t add a trailing slash or the URL alias won\'t work.'),
    );
    if ($path) {
      $form['path']['pid'] = array(
        '#type' => 'value',
        '#value' => db_result(db_query("SELECT pid FROM {url_alias} WHERE dst = '%s'", $path))
      );
    }
  }
}


/**
 * Implementation of hook_perm().
 */
function path_perm() {
  return array('create url aliases', 'administer url aliases');
}

/**
 * Return a listing of all defined URL aliases.
 */
function path_overview() {
  $sql = 'SELECT * FROM {url_alias}';
  $header = array(
    array('data' => fo_1_text('Alias'), 'field' => 'dst', 'sort' => 'asc'),
    array('data' => fo_1_text('System'), 'field' => 'src'),
    array('data' => fo_1_text('Operations'), 'colspan' => '2')
  );
  $sql .= tablesort_sql($header);
  $result = pager_query($sql, 50);

  $destination = fo_1_get_destination();
  while ($data = db_fetch_object($result)) {
    $rows[] = array(fo_1_check_plain($data->dst), fo_1_check_plain($data->src), fo_1_link(fo_1_text('edit'), "admin/path/edit/$data->pid", array(), $destination), fo_1_link(fo_1_text('delete'), "admin/path/delete/$data->pid", array(), $destination));
  }

  if (!$rows) {
    $rows[] = array(array('data' => fo_1_text('No URL aliases available.'), 'colspan' => '4'));
  }

  $output = theme('table', $header, $rows);
  $output .= theme('pager', NULL, 50, 0);
  return $output;
}

/**
 * Fetch a specific URL alias from the database.
 */
function path_load($pid) {
  return db_fetch_array(db_query('SELECT * FROM {url_alias} WHERE pid = %d', $pid));
}

/**
 * Verify that URL alias is valid.
 */
function path_form_validate($form_id, $edit) {
  $src = $edit['src'];
  $dst = $edit['dst'];
  $pid = $edit['pid'];

  if (!fo_1_valid_url($src)) {
    form_set_error('src', fo_1_text('The system path %path is invalid.', array('%path' => theme('placeholder', $src))));
  }

  if (!fo_1_valid_url($dst)) {
    form_set_error('dst', fo_1_text('The alias %alias is invalid.', array('%alias' => theme('placeholder', $dst))));
  }

  if (db_result(db_query("SELECT COUNT(dst) FROM {url_alias} WHERE pid != %d AND dst = '%s'", $pid, $dst))) {
    form_set_error('dst', fo_1_text('The alias %alias is already in use.', array('%alias' => theme('placeholder', $dst))));
  }
}

/**
 * Save URL alias to the database.
 */
function path_form_submit($form_id, $edit) {
  $src = $edit['src'];
  $dst = $edit['dst'];
  $pid = $edit['pid'];

  path_set_alias($src, $dst, $pid);

  fo_1_set_message(fo_1_text('The alias has been saved.'));
  return 'admin/path';
}


